### ISSUE TITLE
Input files should be parsed out

### ISSUE THREAD

**Issue by bmarron18** [LANDIS-II-Foundation/Core-Model#11]
Parse out all input files (including disturbance and output) before spin-up (per rmscheller).

**Comment by rmscheller** [comment]
This request will require careful consideration of order of operations.  Succession would have to be initialized last.  It may not be possible.

**Comment by rmscheller** [comment]
Question:  Can the Core prioritize which extensions are read in in which order?  If so, have the succession extension read in last, which would resolve this issue.

**Comment by VSchuster** [comment]
Succession extension MUST be initialized first before any other disturbance and output extensions are initialized. This is due to the reliance of succession extension from other extensions.

This issue can be closed.
