### ISSUE TITLE
Replace “Ageing cohorts” with “Growing cohorts”

### ISSUE THREAD

**Issue by bmarron18** [LANDIS-II-Foundation/Core-Model#13]
Replace “Ageing cohorts” with “Growing cohorts” in the console when running succession extensions (per rmscheller)

**Comment by rmscheller** [comment]
Note: This is just a labeling change.  If not in the Core, look in the Succession library.

**Comment by VSchuster** [comment]
Found in succession library. I created a new issue there. This one can be closed.

**Comment by rmscheller** [comment]
So closed.
