### ISSUE TITLE
command line 'landis' replaced by 'landis-ii'.  Both options should be available.

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Core-Model#29]
During the last build (6.2.1), the keyword 'landis' was replaced with 'landis-ii'.  Some users would like to be able to use either.  Documentation should reflect this change.

**Comment by rmscheller** [comment]
Is this true?  Bruce and I think it was always 'landis-ii'.

**Comment by rmscheller** [comment]
Verified that it has always been 'landis-ii'.

**Comment by brmiranda** [comment]
The command 'landis' has always been able to run scenarios.  It just ends up running the 'landis-ii' command, but it's always been an option.  Every script I've ever written has just used 'landis', and until I upgraded to this latest release they worked fine.  And in fact, the workbook exercise on replication uses the command 'landis' exclusively in the provided batch files.  I would like to lobby for both options to be supported again.  There are probably other users like me that have always used 'landis' and would need to revise many scripts to enable them to run again.
